class collectd::plugin::tail (
  $ensure         = present
) {
  include collectd::params

  $conf_dir = $collectd::params::plugin_conf_dir

  concat { "${conf_dir}/tail.conf":
    ensure  => $collectd::plugin::tail::ensure,
    owner   => root,
    group   => root,
    mode    => 644,
    notify  => Service['collectd']
  }

  concat::fragment { 'collectd.tail.header.conf':
    target  => "${conf_dir}/tail.conf",
    content => "# Generated by Puppet\n\nLoadPlugin tail\n<Plugin 'tail'>",
  }

  concat::fragment { 'collectd.tail.footer.conf':
    target  => "${conf_dir}/tail.conf",
    content => "</Plugin>",
  }
}
